// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqY3T6zrLsrMdbkwC0AWutSo2XLSwnPg',
    appId: '1:1012382906514:web:52c8618effdf9e940b8e4b',
    messagingSenderId: '1012382906514',
    projectId: 'ice-creamery-9c1e6',
    authDomain: 'ice-creamery-9c1e6.firebaseapp.com',
    storageBucket: 'ice-creamery-9c1e6.firebasestorage.app',
    measurementId: 'G-8DRJYYZ4N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5523GYqK49_t0Z9X3gCIOkEgq8AFdURE',
    appId: '1:1012382906514:android:4562f4f89829e8c20b8e4b',
    messagingSenderId: '1012382906514',
    projectId: 'ice-creamery-9c1e6',
    storageBucket: 'ice-creamery-9c1e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpXwV_sdA3aPHb52HCLhG0N18j8f1Zrp0',
    appId: '1:1012382906514:ios:a0403febe036c57a0b8e4b',
    messagingSenderId: '1012382906514',
    projectId: 'ice-creamery-9c1e6',
    storageBucket: 'ice-creamery-9c1e6.firebasestorage.app',
    iosBundleId: 'com.example.iceCreamery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpXwV_sdA3aPHb52HCLhG0N18j8f1Zrp0',
    appId: '1:1012382906514:ios:a0403febe036c57a0b8e4b',
    messagingSenderId: '1012382906514',
    projectId: 'ice-creamery-9c1e6',
    storageBucket: 'ice-creamery-9c1e6.firebasestorage.app',
    iosBundleId: 'com.example.iceCreamery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkqY3T6zrLsrMdbkwC0AWutSo2XLSwnPg',
    appId: '1:1012382906514:web:8cc5fe446c4f6e560b8e4b',
    messagingSenderId: '1012382906514',
    projectId: 'ice-creamery-9c1e6',
    authDomain: 'ice-creamery-9c1e6.firebaseapp.com',
    storageBucket: 'ice-creamery-9c1e6.firebasestorage.app',
    measurementId: 'G-RZ6SFE2GGR',
  );
}
